### ISSUE TITLE
Potential logic bug: renaming an emptied directory fails

### ISSUE THREAD

**Issue by squizz617** [mit-pdos/fscq#13] opened 2019-04-09 01:34 UTC
Hi.
While testing FSCQ, I came across this potential logic bug:
Directory `A` is considered "not empty" after an inode `A/foo` is created then unlinked, thus prohibiting any other directory from being renamed to `A`.

To test, first create an empty disk image, and mount it at `/tmp/mnt`.
Then, compile and run the following PoC:
```
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <stdlib.h>
#include <unistd.h>
#include <fcntl.h>
#include <string.h>
#include <stdio.h>
#include <errno.h>

int main(int argc, char *argv[])
{
    chdir("/tmp/mnt");

    syscall(SYS_mkdir, "A");
    int fd_A = syscall(SYS_open, "A", O_DIRECTORY, 0);
    int fd_foo = syscall(SYS_open, "A/foo", O_CREAT | O_RDWR, 0777);
    syscall(SYS_unlink, "A/foo");

    syscall(SYS_fsync, fd_foo);
    syscall(SYS_fsync, fd_A);

    syscall(SYS_mkdir, "B");
    int ret = syscall(SYS_rename, "B", "A");
    if (ret < 0)
        printf("rename B A failed: %d (%s)\n", errno, strerror(errno));
    return 0;
}
```
The output is `rename B A failed: 39 (Directory not empty)`, even though the directory `A` is emptied and explicitly `fsync`ed.
```
$ tree mnt
mnt
├── A
└── B

2 directories, 0 files
```

**Comment by tchajed** [comment] 2019-04-09 01:51
This code unlinks an open file and then issues an `fsync` against the old fd; the rename orphans `fd_foo`.

FSCQ's specification doesn't model open file descriptors to even capture this situation, and FUSE would make it difficult to say what the actual behavior would be anyway.

If you fsync and close fd_foo before unlinking `A/foo` then FSCQ performs this rename correctly.

**Comment by squizz617** [comment] 2019-04-09 03:00
I see. Thanks for the comment.

An interesting observation is that `rename` succeeds when the same test case is executed on many other file systems, including `ext4`, `xfs`, `btrfs`, and `f2fs`. 

As you would probably know, POSIX entry for `unlink` states that "if one or more processes have the file open when the last link is removed, the **link shall be removed** before unlink() returns, but the removal of the **file contents** shall be postponed until all references to the file are closed."

So, does this mismatch of behaviors is something that result from different interpretation of POSIX specs?

**Comment by tchajed** [comment] 2019-04-09 15:52
FSCQ doesn't fully implement POSIX, especially around file handles. As you point out, the standard is clear for this example, and FSCQ deviates from the standard. Part of this is due to the complexity of modeling interactions with the operating system (eg, processes each have a directory handle to the current working directory, which needs to be modeled, not to mention their open file handles). Part of it is also that the interaction with FUSE makes it even more difficult to have full control over how a filesystem interacts with the OS.

This issue is somewhat fixable If you pass the option `hard_remove` as part of the `-o` argument to `fscq`. The issue is that FUSE by default implements unlink when there are open handles as a rename to `.fuse_hiddenXXXXX`, so that the filesystem doesn't have to deal with deleting a file's contents only when the last handle is closed. This generally makes FSCQ work closer to the POSIX standard; if you turn on `hard_remove`, interacting with an open but unlinked file will fail, which is also not POSIX compliant. 

You might want to try running the [fuse passthrough filesystem](https://github.com/libfuse/libfuse/blob/master/example/passthrough.c) on top of ext4 and seeing what that does, especially with a variety of FUSE configurations (that is, read the options on [fuse.h](https://github.com/libfuse/libfuse/blob/master/include/fuse.h) and see what you can toggle). I wouldn't be surprised if you find a lot of bugs there.

**Comment by tchajed** [comment] 2019-07-29 13:41
Closing. This behavior falls outside FSCQ's specification. It would be difficult to match other filesystems while using the existing FUSE interface, and I'm not sure FUSE filesystems are ever compliant in the way you're expecting.

**Closed** 2019-07-29 13:41 UTC
